name: Check if product is available
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  product_available:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm i
      - run: npm watch
