name: Check if product is available
on:
  # schedule:
  #  - cron: "* * * * *"
  workflow_dispatch:
jobs:
  product_available:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install npm
        run: npm i
      - name: Run test
        run: npm run watch
      - name: Send Discord message
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilschidur/action-discord@master
        with:
          args: "Test Message"
